###################################################
#Author: Almir Candido                            #
#Contact: https://br.linkedin.com/in/almircandido #
#                                                 #
#Ansible Version: 2.9                             #
#                                                 #
#Requirements:                                    #
#Install:                                         #
#pip install dopy                                 #
###################################################

#################################################
#                                               #
#                 REGIONS                       # 
#################################################
#NYC1, NYC2, NYC3 # New York City, United States#
#AMS2, AMS3:      # Amsterdam, the Netherlands  #
#SFO1, SFO2, SFO3 # San Francisco, United States#
#SGP1             # Singapore                   #
#LON1             # London, United Kingdom      #
#FRA1             # Frankfurt, Germany          #
#TOR1             # Toronto, Canada             #
#BLR1             # Bangalore, India            #
#################################################

########################################################
#                                                      #
#                     IMAGES                           #
########################################################
#Ubuntu       # ubuntu-16-04-x32, ubuntu-16-04-x64,    #
#             # ubuntu-18-04-x64, ubuntu-19-10-x64,    #
#             # ubuntu-20-04-x64                       #
########################################################
#FreeBSD      # freebsd-11-x64-ufs, freebsd-11-x64-zfs,#
#             # freebsd-12-x64, freebsd-12-x64-zfs     #
########################################################
#Fedora       # fedora-30-x64, fedora-31-x64,          #
#             # fedora-32-x64                          #
########################################################
#Debian       # debian-10-x64, debian-9-x64            #
########################################################
#CentOS       # centos-6-x32, centos-6-x64,            #
#             #  centos-7-x64, centos-8-x64            # 
########################################################

#Documentation about modules
#https://docs.ansible.com/ansible/latest/modules/digital_ocean_domain_module
#Digital Ocean create new Droplet

---
- hosts: localhost
  gather_facts: false
  vars:
    API: xxxxxxxxxxxxxxxxxxxx #inform your token
    DROPLET_NAME: webserver01
    DROPLET_SIZE: 1gb
    DROPLET_REGION: tor1
    DROPLET_IMAGE: centos-7-x64
    SSH_KEY_FINGERPRINT: ff:d5:e6:44:45:a1:34:1b:a5:24:g7:b9:cc:00:13:q2 
  tasks:
    - name: Create a new droplet {{ DROPLET_NAME }}
      digital_ocean_droplet:
        oauth_token: "{{ API }}"
        name: "{{ DROPLET_NAME }}"
        size: "{{ DROPLET_SIZE }}"
        region: "{{ DROPLET_REGION }}"
        image: "{{ DROPLET_IMAGE }}"
        wait_timeout: 500
        state: present
        ssh_keys: "{{ SSH_KEY_FINGERPRINT }}" 
      register: new_droplet
#
    - name: New Droplet
      debug:
        var: new_droplet
...
